export const subcategoryLayout = {
  "Ray-finned Fish": { offset: 0, spacing: 32 },
  "Jawless Fishes": { offset: 150, spacing: 32 },
  "Fleshy-Lobed Fishes": { offset: 300, spacing: 32 },
  "Cartilaginous fishes": { offset: 600, spacing: 32 },
  "Armored Sharks": { offset: 900, spacing: 32 },
  "Turtles": { offset: 450, spacing: 32 },
  "Flying Reptiles": { offset: 300, spacing: 32 },
  "Crocodiles": { offset: 500, spacing: 32 },
  "Early Diapsids": { offset: 750, spacing: 32 },
  "Marine Reptiles": { offset: 900, spacing: 32 },
  "Small Carnivores": { offset: 100, spacing: 32 },
  "Long Necked Dinosaurs": { offset: 600, spacing: 32 },
  "Large Carnivores": { offset: 100, spacing: 32 },
  "Horned Dinosaurs": { offset: 150, spacing: 32 },
  "Bird-hipped Dinosaurs": { offset: 750, spacing: 32 },
  "Early Ruling Reptiles": { offset: 100, spacing: 32 },
  "Early Reptiles": { offset: 900, spacing: 32 },
  "early herbivores": { offset: 150, spacing: 32 },
  "Duckbilled Dinosaurs": { offset: 450, spacing: 32 },
  "Armored Dinosaurs": { offset: 300, spacing: 32 },
  "Amphibians": { offset: 300, spacing: 32 },
};
